CREATE TABLE income(
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(80) NOT NULL,
    price INT(11) NOT NULL,
    calen DATE NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE outcome(
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(80) NOT NULL,
    target VARCHAR(80) NOT NULL,
    price INT(11) NOT NULL,
    calen DATE NOT NULL,
    PRIMARY KEY(id)
);